TRAIN:
  SEQ_LEN: 10 
  STRIDE: 1
  VAL_EVAL_INTERVAL: 1
  LOG_INTERVAL: 200

TEST:
  SPLIT: val

ADDONS:
  RUN:
    PHASE: "0"
    DEVICE: "cuda"

    LOG_DIR: "log"
    LOG_FILE_TEMPLATE: "train_temporal_pp_{tag}.txt"

    VIS_DIR: "log/vis"
    VIS_EVERY_SEQS: 200
    VIS_TAG_TEMPLATE: "ep{epoch}_seq{seq:05d}"
    VIS_B: 0

    CKPT_DIR: "log/ckpt"

    # either one of RESUME_CKPT and PRETRAINED_PP_CKPT can be set to non-null
    # RESUME_CKPT: "/home/cernanskyr/pp_xmem_det/log/ckpt/phase0_only_seq8_epoch_5.pth"
    RESUME_CKPT: null
    # PRETRAINED_PP_CKPT: null
    PRETRAINED_PP_CKPT: "/home/cernanskyr/OpenPCDet/output/cfgs/nuscenes_models/cbgs_dyn_pp_centerpoint/dynpp_centerpoint_pretrain/ckpt/checkpoint_epoch_20.pth"

    USE_CKPT_EPOCH: true
    RESUME_OPTIM_SCHED: false

  DATALOADER:
    BATCH_SIZE: 1
    SHUFFLE: true
    PIN_MEMORY: true
    DROP_LAST: false

  TRAIN_LOOP:
    STATS_WINDOW: 500
    LOG_EVERY: 50
    MAX_GRAD_NORM: 10.0

    FORCE_TEACHER_ON_T0: true
    BURN_IN_TEACHER_FORCE: false
    BURN_IN_OCC_CORRUPT: false

    OCC_DROP_RATE: 0.5
    OCC_BLOCK: 8
    XMEM_PREV_THR: 0.5

  PHASES:
    "0":
      PREFIXES: ["bank", "dense_head"]

      START_EPOCH: 0
      END_EPOCH: 1 

      LR_START: 3e-5
      LR_MAX: 3e-5
      LR_END: 3e-8
      WARMUP_EPOCHS: 0

      ALPHA_START: 1.0  
      ALPHA_END: 1.0
      ALPHA_RAMP_EPOCHS: 5

      PROB_SCHEDULE:
        TEACHER:
          START: 1.0
          END: 1.0
          RAMP_EPOCHS: 1

      OPT_GROUP_SPECS:
        - PREFIXES: ["dense_head"]
          LR_MULT: 1.0
        - PREFIXES: ["bank"]
          LR_MULT: 1.0
        - PREFIXES: ["backbone_2d"]
          LR_MULT: 0.0

      CKPT_NAME_TEMPLATE: "phase{phase}_{tag}_epoch_{epoch}.pth"

    "1":
      PREFIXES: ['bank.', 'dense_head.', 'backbone_2d.']
      START_EPOCH: 0
      END_EPOCH: 8

      LR_START: 2e-5
      LR_MAX: 2e-5
      LR_END: 3e-7
      WARMUP_EPOCHS: 0

      ALPHA_START: 1.0  
      ALPHA_END: 1.0
      ALPHA_RAMP_EPOCHS: 5

      PROB_SCHEDULE:
        TEACHER:
          START: 1.0
          END: 1.0
          RAMP_EPOCHS: 1
      
      OPT_GROUP_SPECS:
        - PREFIXES: ['bank.']
          LR_MULT: 1.0
        - PREFIXES: ['dense_head.']
          LR_MULT: 0.5  # Let head adapt
        - PREFIXES: ['backbone_2d.']
          LR_MULT: 0.1

      CKPT_NAME_TEMPLATE: "phase{phase}_{tag}_epoch_{epoch}.pth"

    "2":
      PREFIXES: ['bev_adapter', 'dense_head', 'readout_to_bev',  'xmem']

      START_EPOCH: 13
      END_EPOCH: 18

      LR_START: 5e-6
      LR_MAX: 2e-4
      LR_END: 2e-6
      WARMUP_EPOCHS: 1

      ALPHA_START: 0.2
      ALPHA_END: 0.7
      ALPHA_RAMP_EPOCHS: 5

      PROB_SCHEDULE:
        TEACHER:
          START: 1.0
          END: 1.0
          RAMP_EPOCHS: 1

      OPT_GROUP_SPECS:
        - PREFIXES: ["xmem"]
          LR_MULT: 0.6
        - PREFIXES: ["hidden_to_bev"]
          LR_MULT: 1.0
        - PREFIXES: ["dense_head"]
          LR_MULT: 1.0
        - PREFIXES: ["backbone_2d"]
          LR_MULT: 0.0

      CKPT_NAME_TEMPLATE: "phase{phase}_{tag}_epoch_{epoch}.pth"

    "3":
      PREFIXES: ['bev_adapter', 'dense_head', 'readout_to_bev',  'xmem']

      START_EPOCH: 18
      END_EPOCH: 20

      LR_START: 2e-6
      LR_MAX: 5e-5
      LR_END: 1e-6
      WARMUP_EPOCHS: 0

      ALPHA_START: 0.6
      ALPHA_END: 0.6
      ALPHA_RAMP_EPOCHS: 1

      PROB_SCHEDULE:
        TEACHER:
          START: 1.0
          END: 1.0
          RAMP_EPOCHS: 1

      OPT_GROUP_SPECS:
        - PREFIXES: ["xmem"]
          LR_MULT: 0.6
        - PREFIXES: ["hidden_to_bev"]
          LR_MULT: 1.0
        - PREFIXES: ["dense_head"]
          LR_MULT: 1.0
        - PREFIXES: ["backbone_2d"]
          LR_MULT: 0.0

      CKPT_NAME_TEMPLATE: "phase{phase}_{tag}_epoch_{epoch}.pth"


CLASS_NAMES: ['car','truck', 'construction_vehicle', 'bus', 'trailer',
              'barrier', 'motorcycle', 'bicycle', 'pedestrian', 'traffic_cone']

DATA_CONFIG:
    _BASE_CONFIG_: xmem_det/configs/nuscenes_dataset.yaml

    POINT_CLOUD_RANGE: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True

        -   NAME: shuffle_points
            SHUFFLE_ENABLED: {
                'train': True,
                'test': True
            }

        -   NAME: transform_points_to_voxels_placeholder
            VOXEL_SIZE: [0.2, 0.2, 8.0]

MODEL:
    NAME: CenterPoint

    VFE:
        NAME: DynPillarVFE
        WITH_DISTANCE: False
        USE_ABSLOTE_XYZ: True
        USE_NORM: True
        NUM_FILTERS: [ 64, 64 ]

    MAP_TO_BEV:
        NAME: PointPillarScatter
        NUM_BEV_FEATURES: 64

    BACKBONE_2D:
        NAME: BaseBEVBackbone
        LAYER_NUMS: [3, 5, 5]
        LAYER_STRIDES: [2, 2, 2]
        NUM_FILTERS: [64, 128, 256]
        UPSAMPLE_STRIDES: [0.5, 1, 2]
        NUM_UPSAMPLE_FILTERS: [128, 128, 128]

    DENSE_HEAD:
        NAME: CenterHead
        CLASS_AGNOSTIC: False

        CLASS_NAMES_EACH_HEAD: [
            ['car'], 
            ['truck', 'construction_vehicle'],
            ['bus', 'trailer'],
            ['barrier'],
            ['motorcycle', 'bicycle'],
            ['pedestrian', 'traffic_cone'],
        ]

        SHARED_CONV_CHANNEL: 64
        USE_BIAS_BEFORE_NORM: True
        NUM_HM_CONV: 2
        SEPARATE_HEAD_CFG:
            HEAD_ORDER: ['center', 'center_z', 'dim', 'rot', 'vel']
            HEAD_DICT: {
                'center': {'out_channels': 2, 'num_conv': 2},
                'center_z': {'out_channels': 1, 'num_conv': 2},
                'dim': {'out_channels': 3, 'num_conv': 2},
                'rot': {'out_channels': 2, 'num_conv': 2},
                'vel': {'out_channels': 2, 'num_conv': 2},
            }

        TARGET_ASSIGNER_CONFIG:
            FEATURE_MAP_STRIDE: 4
            NUM_MAX_OBJS: 500
            GAUSSIAN_OVERLAP: 0.1
            MIN_RADIUS: 2

        LOSS_CONFIG:
            LOSS_WEIGHTS: {
                'cls_weight': 1.0,
                'loc_weight': 0.25,
                'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2, 1.0, 1.0]
            }

        POST_PROCESSING:
            SCORE_THRESH: 0.1
            POST_CENTER_LIMIT_RANGE: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
            MAX_OBJ_PER_SAMPLE: 500
            NMS_CONFIG:
                NMS_TYPE: nms_gpu
                NMS_THRESH: 0.2
                NMS_PRE_MAXSIZE: 1000
                NMS_POST_MAXSIZE: 83

    POST_PROCESSING:
        RECALL_THRESH_LIST: [0.3, 0.5, 0.7]

        EVAL_METRIC: kitti


OPTIMIZATION:
  BATCH_SIZE_PER_GPU: 1 
  NUM_EPOCHS: 20 
  NUM_WORKERS: 4
  LR: 0.001
  WEIGHT_DECAY: 0.01
  MOMENTUM: 0.9
